name: "Push Image Scan"

on:
  push:
    branches:
      - main
    # もしこのリポジトリ自体の変更だけを対象にする場合、特定のパスを除外することも可能です
    #paths-ignore:
    #   - .github/workflows/scheduled-scan.yaml

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ghcr.io/eridon-pro/go-helloworld-3:latest
          #- ghcr.io/eridon-pro/another-image:latest
          # 他のイメージをここに追加

    steps:
      - name: Checkout scan config
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL

      - name: Image Scan Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Image Scan Completed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Image Scan Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Image Scan Failed! Check PR Log.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Image Scan Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Image Scan Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
