name: "Scheduled Image Scan"

on:
  schedule:
    - cron: "0 5 * * *"  # 毎日午前2時に実行
  push:
    branches:
      - main
    paths:
      - .github/workflows/scheduled-scan.yaml  # このファイルが更新された場合にのみ実行

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ghcr.io/eridon-pro/go-helloworld-3:latest
          #- ghcr.io/eridon-pro/another-image:latest
          # 他のイメージをここに追加

    steps:
      - name: Checkout scan config
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.image }}
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL

      - name: Notify Discord on Scan Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: "Scheduled scan completed successfully!"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Notify Discord on Scan Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: "Scheduled scan failed! Please check the logs."
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      - name: Notify Discord on Scan Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: "Scheduled scan cancelled!"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
